//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebISB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banhanhvb
    {
        public System.Guid Id { get; set; }
        public System.Guid Idvanban { get; set; }
        public string Donvinhan { get; set; }
        public Nullable<System.DateTime> Ngayphathanh { get; set; }
        public string Nguoibanhanh { get; set; }
    
        public virtual vanban vanban { get; set; }
    }
}
