//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebISB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ISBEntities : DbContext
    {
        public ISBEntities()
            : base("name=ISBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<loaitin> loaitins { get; set; }
        public virtual DbSet<slide> slides { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<theloai> theloais { get; set; }
        public virtual DbSet<tintuc> tintucs { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<lienhe> lienhes { get; set; }
        public virtual DbSet<gioithieu> gioithieux { get; set; }
        public virtual DbSet<loaivanban> loaivanbans { get; set; }
        public virtual DbSet<DonVi> DonVis { get; set; }
        public virtual DbSet<Banhanhvb> Banhanhvbs { get; set; }
        public virtual DbSet<vanban> vanbans { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<loaitailieu> loaitailieux { get; set; }
        public virtual DbSet<tailieu> tailieux { get; set; }
    
        public virtual ObjectResult<FN_Get_TinTuc_Result> FN_Get_TinTuc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_TinTuc_Result>("FN_Get_TinTuc");
        }
    
        public virtual ObjectResult<tintuc> FN_Update_TinTuc(string tieuDe, string tieuDeKhongDau, string tomTat, string noiDung, string imagePath, Nullable<int> noiBat, Nullable<int> idLoaiTin, Nullable<System.DateTime> updated_at, Nullable<int> id)
        {
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var tieuDeKhongDauParameter = tieuDeKhongDau != null ?
                new ObjectParameter("TieuDeKhongDau", tieuDeKhongDau) :
                new ObjectParameter("TieuDeKhongDau", typeof(string));
    
            var tomTatParameter = tomTat != null ?
                new ObjectParameter("TomTat", tomTat) :
                new ObjectParameter("TomTat", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var imagePathParameter = imagePath != null ?
                new ObjectParameter("ImagePath", imagePath) :
                new ObjectParameter("ImagePath", typeof(string));
    
            var noiBatParameter = noiBat.HasValue ?
                new ObjectParameter("NoiBat", noiBat) :
                new ObjectParameter("NoiBat", typeof(int));
    
            var idLoaiTinParameter = idLoaiTin.HasValue ?
                new ObjectParameter("IdLoaiTin", idLoaiTin) :
                new ObjectParameter("IdLoaiTin", typeof(int));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("Updated_at", updated_at) :
                new ObjectParameter("Updated_at", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tintuc>("FN_Update_TinTuc", tieuDeParameter, tieuDeKhongDauParameter, tomTatParameter, noiDungParameter, imagePathParameter, noiBatParameter, idLoaiTinParameter, updated_atParameter, idParameter);
        }
    
        public virtual ObjectResult<tintuc> FN_Update_TinTuc(string tieuDe, string tieuDeKhongDau, string tomTat, string noiDung, string imagePath, Nullable<int> noiBat, Nullable<int> idLoaiTin, Nullable<System.DateTime> updated_at, Nullable<int> id, MergeOption mergeOption)
        {
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var tieuDeKhongDauParameter = tieuDeKhongDau != null ?
                new ObjectParameter("TieuDeKhongDau", tieuDeKhongDau) :
                new ObjectParameter("TieuDeKhongDau", typeof(string));
    
            var tomTatParameter = tomTat != null ?
                new ObjectParameter("TomTat", tomTat) :
                new ObjectParameter("TomTat", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var imagePathParameter = imagePath != null ?
                new ObjectParameter("ImagePath", imagePath) :
                new ObjectParameter("ImagePath", typeof(string));
    
            var noiBatParameter = noiBat.HasValue ?
                new ObjectParameter("NoiBat", noiBat) :
                new ObjectParameter("NoiBat", typeof(int));
    
            var idLoaiTinParameter = idLoaiTin.HasValue ?
                new ObjectParameter("IdLoaiTin", idLoaiTin) :
                new ObjectParameter("IdLoaiTin", typeof(int));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("Updated_at", updated_at) :
                new ObjectParameter("Updated_at", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tintuc>("FN_Update_TinTuc", mergeOption, tieuDeParameter, tieuDeKhongDauParameter, tomTatParameter, noiDungParameter, imagePathParameter, noiBatParameter, idLoaiTinParameter, updated_atParameter, idParameter);
        }
    
        public virtual ObjectResult<FN_Get_TinTuc_Trash_Result> FN_Get_TinTuc_Trash()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_TinTuc_Trash_Result>("FN_Get_TinTuc_Trash");
        }
    
        public virtual ObjectResult<FN_Get_LoaiTin_Result> FN_Get_LoaiTin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_LoaiTin_Result>("FN_Get_LoaiTin");
        }
    
        public virtual ObjectResult<Get_LoaiTin_Trash_Result> Get_LoaiTin_Trash()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_LoaiTin_Trash_Result>("Get_LoaiTin_Trash");
        }
    
        public virtual ObjectResult<FN_Get_LoaiTin_Trash_Result> FN_Get_LoaiTin_Trash()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_LoaiTin_Trash_Result>("FN_Get_LoaiTin_Trash");
        }
    
        public virtual ObjectResult<Get_TheLoai_Result> Get_TheLoai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TheLoai_Result>("Get_TheLoai");
        }
    
        public virtual ObjectResult<FN_Get_TheLoai_Result> FN_Get_TheLoai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_TheLoai_Result>("FN_Get_TheLoai");
        }
    
        public virtual int Update_Loaitin_Status(Nullable<int> idTheLoai, Nullable<int> up)
        {
            var idTheLoaiParameter = idTheLoai.HasValue ?
                new ObjectParameter("idTheLoai", idTheLoai) :
                new ObjectParameter("idTheLoai", typeof(int));
    
            var upParameter = up.HasValue ?
                new ObjectParameter("up", up) :
                new ObjectParameter("up", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Loaitin_Status", idTheLoaiParameter, upParameter);
        }
    
        public virtual int FN_Update_Loaitin_Status(Nullable<int> idTheLoai, Nullable<int> up)
        {
            var idTheLoaiParameter = idTheLoai.HasValue ?
                new ObjectParameter("idTheLoai", idTheLoai) :
                new ObjectParameter("idTheLoai", typeof(int));
    
            var upParameter = up.HasValue ?
                new ObjectParameter("up", up) :
                new ObjectParameter("up", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_Update_Loaitin_Status", idTheLoaiParameter, upParameter);
        }
    
        public virtual int Update_Tintuc_Status(Nullable<int> idLoaiTin, Nullable<int> up)
        {
            var idLoaiTinParameter = idLoaiTin.HasValue ?
                new ObjectParameter("idLoaiTin", idLoaiTin) :
                new ObjectParameter("idLoaiTin", typeof(int));
    
            var upParameter = up.HasValue ?
                new ObjectParameter("up", up) :
                new ObjectParameter("up", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Tintuc_Status", idLoaiTinParameter, upParameter);
        }
    
        public virtual int FN_Update_Tintuc_Status(Nullable<int> idLoaiTin, Nullable<int> up)
        {
            var idLoaiTinParameter = idLoaiTin.HasValue ?
                new ObjectParameter("idLoaiTin", idLoaiTin) :
                new ObjectParameter("idLoaiTin", typeof(int));
    
            var upParameter = up.HasValue ?
                new ObjectParameter("up", up) :
                new ObjectParameter("up", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_Update_Tintuc_Status", idLoaiTinParameter, upParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Count_status(Nullable<int> iD, Nullable<int> tT_S)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tT_SParameter = tT_S.HasValue ?
                new ObjectParameter("TT_S", tT_S) :
                new ObjectParameter("TT_S", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Count_status", iDParameter, tT_SParameter);
        }
    
        public virtual int FN_Count_status(Nullable<int> iD, Nullable<int> tT_S)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tT_SParameter = tT_S.HasValue ?
                new ObjectParameter("TT_S", tT_S) :
                new ObjectParameter("TT_S", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_Count_status", iDParameter, tT_SParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Count_status_Lt(Nullable<int> iD, Nullable<int> tT_S)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tT_SParameter = tT_S.HasValue ?
                new ObjectParameter("TT_S", tT_S) :
                new ObjectParameter("TT_S", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Count_status_Lt", iDParameter, tT_SParameter);
        }
    
        public virtual int FN_Count_status_Lt(Nullable<int> iD, Nullable<int> tT_S)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tT_SParameter = tT_S.HasValue ?
                new ObjectParameter("TT_S", tT_S) :
                new ObjectParameter("TT_S", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_Count_status_Lt", iDParameter, tT_SParameter);
        }
    
        public virtual ObjectResult<Get_TheLoai_Trash_Result> Get_TheLoai_Trash()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TheLoai_Trash_Result>("Get_TheLoai_Trash");
        }
    
        public virtual ObjectResult<FN_Get_TheLoai_Trash_Result> FN_Get_TheLoai_Trash()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_TheLoai_Trash_Result>("FN_Get_TheLoai_Trash");
        }
    
        public virtual int Delete_Loaitin_TinTuc(Nullable<int> idTheLoai)
        {
            var idTheLoaiParameter = idTheLoai.HasValue ?
                new ObjectParameter("idTheLoai", idTheLoai) :
                new ObjectParameter("idTheLoai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Loaitin_TinTuc", idTheLoaiParameter);
        }
    
        public virtual int FN_Delete_TinTuc(Nullable<int> idLoaiTin)
        {
            var idLoaiTinParameter = idLoaiTin.HasValue ?
                new ObjectParameter("idLoaiTin", idLoaiTin) :
                new ObjectParameter("idLoaiTin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_Delete_TinTuc", idLoaiTinParameter);
        }
    
        public virtual int FN_Delete_Loaitin_TinTuc(Nullable<int> idTheLoai)
        {
            var idTheLoaiParameter = idTheLoai.HasValue ?
                new ObjectParameter("idTheLoai", idTheLoai) :
                new ObjectParameter("idTheLoai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_Delete_Loaitin_TinTuc", idTheLoaiParameter);
        }
    
        public virtual ObjectResult<Get_Tailieu_Result> Get_Tailieu(string maLoai, string mS_DV)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var mS_DVParameter = mS_DV != null ?
                new ObjectParameter("MS_DV", mS_DV) :
                new ObjectParameter("MS_DV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Tailieu_Result>("Get_Tailieu", maLoaiParameter, mS_DVParameter);
        }
    
        public virtual ObjectResult<FN_Get_Tailieu_Result> FN_Get_Tailieu(string maLoai, string mS_DV)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var mS_DVParameter = mS_DV != null ?
                new ObjectParameter("MS_DV", mS_DV) :
                new ObjectParameter("MS_DV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_Tailieu_Result>("FN_Get_Tailieu", maLoaiParameter, mS_DVParameter);
        }
    
        public virtual ObjectResult<Get_Tailieu_Trash_Result> Get_Tailieu_Trash(string ms_dv)
        {
            var ms_dvParameter = ms_dv != null ?
                new ObjectParameter("ms_dv", ms_dv) :
                new ObjectParameter("ms_dv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Tailieu_Trash_Result>("Get_Tailieu_Trash", ms_dvParameter);
        }
    
        public virtual ObjectResult<FN_Get_Tailieu_Trash_Result> FN_Get_Tailieu_Trash(string ms_dv)
        {
            var ms_dvParameter = ms_dv != null ?
                new ObjectParameter("ms_dv", ms_dv) :
                new ObjectParameter("ms_dv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_Tailieu_Trash_Result>("FN_Get_Tailieu_Trash", ms_dvParameter);
        }
    
        public virtual ObjectResult<Get_Side_Menu_Result> Get_Side_Menu(string idparent)
        {
            var idparentParameter = idparent != null ?
                new ObjectParameter("Idparent", idparent) :
                new ObjectParameter("Idparent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Side_Menu_Result>("Get_Side_Menu", idparentParameter);
        }
    
        public virtual ObjectResult<F_Get_Side_Menu_Result> F_Get_Side_Menu(string idparent)
        {
            var idparentParameter = idparent != null ?
                new ObjectParameter("Idparent", idparent) :
                new ObjectParameter("Idparent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<F_Get_Side_Menu_Result>("F_Get_Side_Menu", idparentParameter);
        }
    
        public virtual ObjectResult<Get_TinTuc_TC_Result> Get_TinTuc_TC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TinTuc_TC_Result>("Get_TinTuc_TC");
        }
    
        public virtual ObjectResult<FN_Get_TinTuc_TC_Result> FN_Get_TinTuc_TC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_TinTuc_TC_Result>("FN_Get_TinTuc_TC");
        }
    
        public virtual ObjectResult<Get_TinTuc_Loai_TC_Result> Get_TinTuc_Loai_TC(string loai, Nullable<int> id)
        {
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TinTuc_Loai_TC_Result>("Get_TinTuc_Loai_TC", loaiParameter, idParameter);
        }
    
        public virtual ObjectResult<FN_Get_TinTuc_Loai_TC_Result> FN_Get_TinTuc_Loai_TC(string loai, Nullable<int> id)
        {
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_TinTuc_Loai_TC_Result>("FN_Get_TinTuc_Loai_TC", loaiParameter, idParameter);
        }
    
        public virtual int Get_Slide_Page()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Get_Slide_Page");
        }
    
        public virtual ObjectResult<slide> FN_Get_Slide_Page()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<slide>("FN_Get_Slide_Page");
        }
    
        public virtual ObjectResult<slide> FN_Get_Slide_Page(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<slide>("FN_Get_Slide_Page", mergeOption);
        }
    
        public virtual ObjectResult<Get_LienHe_Result> Get_LienHe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_LienHe_Result>("Get_LienHe");
        }
    
        public virtual ObjectResult<lienhe> FN_Get_LienHe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lienhe>("FN_Get_LienHe");
        }
    
        public virtual ObjectResult<lienhe> FN_Get_LienHe(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lienhe>("FN_Get_LienHe", mergeOption);
        }
    
        public virtual ObjectResult<Get_GioiThieu_Result> Get_GioiThieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_GioiThieu_Result>("Get_GioiThieu");
        }
    
        public virtual ObjectResult<gioithieu> FN_Get_GioiThieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gioithieu>("FN_Get_GioiThieu");
        }
    
        public virtual ObjectResult<gioithieu> FN_Get_GioiThieu(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gioithieu>("FN_Get_GioiThieu", mergeOption);
        }
    
        public virtual ObjectResult<Get_ChiTietTin_Result> Get_ChiTietTin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_ChiTietTin_Result>("Get_ChiTietTin", idParameter);
        }
    
        public virtual ObjectResult<FN_Get_ChiTietTin_Result> FN_Get_ChiTietTin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_ChiTietTin_Result>("FN_Get_ChiTietTin", idParameter);
        }
    
        public virtual ObjectResult<Get_ChiTietTin_LT_Result> Get_ChiTietTin_LT(Nullable<int> idLT)
        {
            var idLTParameter = idLT.HasValue ?
                new ObjectParameter("idLT", idLT) :
                new ObjectParameter("idLT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_ChiTietTin_LT_Result>("Get_ChiTietTin_LT", idLTParameter);
        }
    
        public virtual ObjectResult<FN_Get_ChiTietTin_LT_Result> FN_Get_ChiTietTin_LT(Nullable<int> idLT)
        {
            var idLTParameter = idLT.HasValue ?
                new ObjectParameter("idLT", idLT) :
                new ObjectParameter("idLT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_ChiTietTin_LT_Result>("FN_Get_ChiTietTin_LT", idLTParameter);
        }
    
        public virtual ObjectResult<Get_ChiTietTin_Noibat_Result> Get_ChiTietTin_Noibat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_ChiTietTin_Noibat_Result>("Get_ChiTietTin_Noibat");
        }
    
        public virtual ObjectResult<FN_Get_ChiTietTin_Noibat_Result> FN_Get_ChiTietTin_Noibat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_ChiTietTin_Noibat_Result>("FN_Get_ChiTietTin_Noibat");
        }
    
        public virtual ObjectResult<get_donvi_Result> get_donvi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_donvi_Result>("get_donvi");
        }
    
        public virtual ObjectResult<FN_get_donvi_Result> FN_get_donvi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_get_donvi_Result>("FN_get_donvi");
        }
    
        public virtual ObjectResult<Get_Banhanhvb_Result> Get_Banhanhvb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Banhanhvb_Result>("Get_Banhanhvb");
        }
    
        public virtual ObjectResult<FN_Get_Banhanhvb_Result> FN_Get_Banhanhvb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_Banhanhvb_Result>("FN_Get_Banhanhvb");
        }
    
        public virtual ObjectResult<Get_Banhanhvb_Tim_Result> Get_Banhanhvb_Tim(string sovb, string noiphathanh, string loaivanban, string trichyeu)
        {
            var sovbParameter = sovb != null ?
                new ObjectParameter("Sovb", sovb) :
                new ObjectParameter("Sovb", typeof(string));
    
            var noiphathanhParameter = noiphathanh != null ?
                new ObjectParameter("Noiphathanh", noiphathanh) :
                new ObjectParameter("Noiphathanh", typeof(string));
    
            var loaivanbanParameter = loaivanban != null ?
                new ObjectParameter("Loaivanban", loaivanban) :
                new ObjectParameter("Loaivanban", typeof(string));
    
            var trichyeuParameter = trichyeu != null ?
                new ObjectParameter("Trichyeu", trichyeu) :
                new ObjectParameter("Trichyeu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Banhanhvb_Tim_Result>("Get_Banhanhvb_Tim", sovbParameter, noiphathanhParameter, loaivanbanParameter, trichyeuParameter);
        }
    
        public virtual ObjectResult<Get_vanbandi_Result> Get_vanbandi(string donvi)
        {
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_vanbandi_Result>("Get_vanbandi", donviParameter);
        }
    
        public virtual ObjectResult<FN_Get_Banhanhvb_Tim_Result> FN_Get_Banhanhvb_Tim(string sovb, string noiphathanh, string loaivanban, string trichyeu)
        {
            var sovbParameter = sovb != null ?
                new ObjectParameter("Sovb", sovb) :
                new ObjectParameter("Sovb", typeof(string));
    
            var noiphathanhParameter = noiphathanh != null ?
                new ObjectParameter("Noiphathanh", noiphathanh) :
                new ObjectParameter("Noiphathanh", typeof(string));
    
            var loaivanbanParameter = loaivanban != null ?
                new ObjectParameter("Loaivanban", loaivanban) :
                new ObjectParameter("Loaivanban", typeof(string));
    
            var trichyeuParameter = trichyeu != null ?
                new ObjectParameter("Trichyeu", trichyeu) :
                new ObjectParameter("Trichyeu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_Banhanhvb_Tim_Result>("FN_Get_Banhanhvb_Tim", sovbParameter, noiphathanhParameter, loaivanbanParameter, trichyeuParameter);
        }
    
        public virtual ObjectResult<FN_Get_vanbandi_Result> FN_Get_vanbandi(string donvi)
        {
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_vanbandi_Result>("FN_Get_vanbandi", donviParameter);
        }
    
        public virtual ObjectResult<Get_Banhanhvb_Tim_vbdi_Result> Get_Banhanhvb_Tim_vbdi(string donvi, string sovb, string noiphathanh, string loaivanban, string trichyeu)
        {
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            var sovbParameter = sovb != null ?
                new ObjectParameter("Sovb", sovb) :
                new ObjectParameter("Sovb", typeof(string));
    
            var noiphathanhParameter = noiphathanh != null ?
                new ObjectParameter("Noiphathanh", noiphathanh) :
                new ObjectParameter("Noiphathanh", typeof(string));
    
            var loaivanbanParameter = loaivanban != null ?
                new ObjectParameter("Loaivanban", loaivanban) :
                new ObjectParameter("Loaivanban", typeof(string));
    
            var trichyeuParameter = trichyeu != null ?
                new ObjectParameter("Trichyeu", trichyeu) :
                new ObjectParameter("Trichyeu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Banhanhvb_Tim_vbdi_Result>("Get_Banhanhvb_Tim_vbdi", donviParameter, sovbParameter, noiphathanhParameter, loaivanbanParameter, trichyeuParameter);
        }
    
        public virtual ObjectResult<FN_Get_Banhanhvb_Tim_vbdi_Result> FN_Get_Banhanhvb_Tim_vbdi(string donvi, string sovb, string noiphathanh, string loaivanban, string trichyeu)
        {
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            var sovbParameter = sovb != null ?
                new ObjectParameter("Sovb", sovb) :
                new ObjectParameter("Sovb", typeof(string));
    
            var noiphathanhParameter = noiphathanh != null ?
                new ObjectParameter("Noiphathanh", noiphathanh) :
                new ObjectParameter("Noiphathanh", typeof(string));
    
            var loaivanbanParameter = loaivanban != null ?
                new ObjectParameter("Loaivanban", loaivanban) :
                new ObjectParameter("Loaivanban", typeof(string));
    
            var trichyeuParameter = trichyeu != null ?
                new ObjectParameter("Trichyeu", trichyeu) :
                new ObjectParameter("Trichyeu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_Banhanhvb_Tim_vbdi_Result>("FN_Get_Banhanhvb_Tim_vbdi", donviParameter, sovbParameter, noiphathanhParameter, loaivanbanParameter, trichyeuParameter);
        }
    
        public virtual ObjectResult<Get_Noibo_vbden_Result> Get_Noibo_vbden(string donVi)
        {
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Noibo_vbden_Result>("Get_Noibo_vbden", donViParameter);
        }
    
        public virtual ObjectResult<FN_Get_Noibo_vbden_Result> FN_Get_Noibo_vbden(string donVi)
        {
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FN_Get_Noibo_vbden_Result>("FN_Get_Noibo_vbden", donViParameter);
        }
    
        public virtual ObjectResult<Get_Banhanhvb_NB_Den_Result> Get_Banhanhvb_NB_Den(string sovb, string noiphathanh, string loaivanban, string trichyeu, string donVi)
        {
            var sovbParameter = sovb != null ?
                new ObjectParameter("Sovb", sovb) :
                new ObjectParameter("Sovb", typeof(string));
    
            var noiphathanhParameter = noiphathanh != null ?
                new ObjectParameter("Noiphathanh", noiphathanh) :
                new ObjectParameter("Noiphathanh", typeof(string));
    
            var loaivanbanParameter = loaivanban != null ?
                new ObjectParameter("Loaivanban", loaivanban) :
                new ObjectParameter("Loaivanban", typeof(string));
    
            var trichyeuParameter = trichyeu != null ?
                new ObjectParameter("Trichyeu", trichyeu) :
                new ObjectParameter("Trichyeu", typeof(string));
    
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Banhanhvb_NB_Den_Result>("Get_Banhanhvb_NB_Den", sovbParameter, noiphathanhParameter, loaivanbanParameter, trichyeuParameter, donViParameter);
        }
    
        public virtual ObjectResult<Get_vanbandi_NoiBo_Result> Get_vanbandi_NoiBo(string donvi)
        {
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_vanbandi_NoiBo_Result>("Get_vanbandi_NoiBo", donviParameter);
        }
    
        public virtual ObjectResult<Get_vanbandi_NoiBo_search_Result> Get_vanbandi_NoiBo_search(string sovb, string loaivanban, string trichyeu, string donvigui, string donViNhan)
        {
            var sovbParameter = sovb != null ?
                new ObjectParameter("Sovb", sovb) :
                new ObjectParameter("Sovb", typeof(string));
    
            var loaivanbanParameter = loaivanban != null ?
                new ObjectParameter("Loaivanban", loaivanban) :
                new ObjectParameter("Loaivanban", typeof(string));
    
            var trichyeuParameter = trichyeu != null ?
                new ObjectParameter("Trichyeu", trichyeu) :
                new ObjectParameter("Trichyeu", typeof(string));
    
            var donviguiParameter = donvigui != null ?
                new ObjectParameter("donvigui", donvigui) :
                new ObjectParameter("donvigui", typeof(string));
    
            var donViNhanParameter = donViNhan != null ?
                new ObjectParameter("DonViNhan", donViNhan) :
                new ObjectParameter("DonViNhan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_vanbandi_NoiBo_search_Result>("Get_vanbandi_NoiBo_search", sovbParameter, loaivanbanParameter, trichyeuParameter, donviguiParameter, donViNhanParameter);
        }
    
        public virtual ObjectResult<Get_Chitietvb_Result> Get_Chitietvb(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Chitietvb_Result>("Get_Chitietvb", idParameter);
        }
    
        public virtual ObjectResult<Get_vanban_dashboard_Result> Get_vanban_dashboard(string donvi)
        {
            var donviParameter = donvi != null ?
                new ObjectParameter("Donvi", donvi) :
                new ObjectParameter("Donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_vanban_dashboard_Result>("Get_vanban_dashboard", donviParameter);
        }
    
        public virtual ObjectResult<Get_banhanhvanban_dashboard_Result> Get_banhanhvanban_dashboard(string donvi)
        {
            var donviParameter = donvi != null ?
                new ObjectParameter("Donvi", donvi) :
                new ObjectParameter("Donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_banhanhvanban_dashboard_Result>("Get_banhanhvanban_dashboard", donviParameter);
        }
    
        public virtual ObjectResult<Get_vanban_cb_Result> Get_vanban_cb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_vanban_cb_Result>("Get_vanban_cb");
        }
    
        public virtual int sp_delVanban(Nullable<System.Guid> idvb)
        {
            var idvbParameter = idvb.HasValue ?
                new ObjectParameter("idvb", idvb) :
                new ObjectParameter("idvb", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delVanban", idvbParameter);
        }
    
        public virtual ObjectResult<Get_loaiVanban_Result> Get_loaiVanban()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_loaiVanban_Result>("Get_loaiVanban");
        }
    
        public virtual ObjectResult<Get_User_Result> Get_User()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_Result>("Get_User");
        }
    
        public virtual ObjectResult<Get_PhanQuyen_Result> Get_PhanQuyen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_PhanQuyen_Result>("Get_PhanQuyen");
        }
    
        public virtual ObjectResult<Get_LoaiTaiLieu_Result> Get_LoaiTaiLieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_LoaiTaiLieu_Result>("Get_LoaiTaiLieu");
        }
    
        public virtual ObjectResult<Get_Tailieu_PhongBan_Result> Get_Tailieu_PhongBan(string maLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Tailieu_PhongBan_Result>("Get_Tailieu_PhongBan", maLoaiParameter);
        }
    
        public virtual ObjectResult<Get_tailieu_admin_Result> Get_tailieu_admin(string ms_dv)
        {
            var ms_dvParameter = ms_dv != null ?
                new ObjectParameter("ms_dv", ms_dv) :
                new ObjectParameter("ms_dv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_tailieu_admin_Result>("Get_tailieu_admin", ms_dvParameter);
        }
    
        public virtual ObjectResult<Get_Banhanhvb_vb_Result> Get_Banhanhvb_vb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Banhanhvb_vb_Result>("Get_Banhanhvb_vb");
        }
    
        public virtual ObjectResult<Get_Chitietvb_vb_Result> Get_Chitietvb_vb(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Chitietvb_vb_Result>("Get_Chitietvb_vb", idParameter);
        }
    
        public virtual ObjectResult<get_loaivanban_dropdownlist_Result> get_loaivanban_dropdownlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_loaivanban_dropdownlist_Result>("get_loaivanban_dropdownlist");
        }
    }
}
