//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebISB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaivanban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loaivanban()
        {
            this.vanbans = new HashSet<vanban>();
        }
    
        public int id { get; set; }
        public string TenLoaiVB { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vanban> vanbans { get; set; }
    }
}
