//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebISB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public string id { get; set; }
        public Nullable<bool> mVanban { get; set; }
        public Nullable<bool> mTheloaiTin { get; set; }
        public Nullable<bool> mLoaiTin { get; set; }
        public Nullable<bool> mTinTuc { get; set; }
        public Nullable<bool> mTaiLieu { get; set; }
        public Nullable<bool> mGioiThieu { get; set; }
        public Nullable<bool> mLienHe { get; set; }
        public Nullable<bool> mLoaivanban { get; set; }
        public Nullable<bool> mQuantri { get; set; }
        public Nullable<bool> Quyen { get; set; }
    }
}
