//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebISB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tailieu
    {
        public int id { get; set; }
        public string TieuDe { get; set; }
        public string TenFile { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> create_up { get; set; }
        public Nullable<short> status { get; set; }
        public string user_create { get; set; }
        public string MaSo { get; set; }
        public string MS_DV { get; set; }
        public string MaLoai { get; set; }
    
        public virtual loaitailieu loaitailieu { get; set; }
        public virtual user user { get; set; }
    }
}
