//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebISB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tintuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tintuc()
        {
            this.comments = new HashSet<comment>();
        }
    
        public int id { get; set; }
        public string TieuDe { get; set; }
        public string TieuDeKhongDau { get; set; }
        public string TomTat { get; set; }
        public string NoiDung { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> NoiBat { get; set; }
        public Nullable<int> SoLuotXem { get; set; }
        public int idLoaiTin { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string User_Create { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        public virtual loaitin loaitin { get; set; }
        public virtual user user { get; set; }
    }
}
